#!/usr/bin/env ruby
$: << __dir__ + '/lib'
require 'bundler/inline'
gemfile do
  gem 'activesupport'
  gem 'rake'
  gem 'duplicate'
  gem 'rspec'
end
require 'active_support'
require 'active_support/core_ext'
require 'enumerable_ext'
require 'letters'

$stdout.sync = true

print "Letters: "
letters = $stdin.gets.chomp

puts Letters::Solver.solutions(letters, min_length: letters.length).unique.to_a
